export const COIN_GECKO_BASE_URL = "https://api.coingecko.com/api/v3";
export const Ox_BASE_URL = "https://api.0x.org";
export const Ox_WS_URL = "wss://stream.binance.com:9443/ws";
export const GECKO_VS_SYMBOLS = [
  "btc",
  "eth",
  "ltc",
  "bch",
  "bnb",
  "eos",
  "xrp",
  "xlm",
  "link",
  "dot",
  "yfi",
  "usd",
  "aed",
  "ars",
  "aud",
  "bdt",
  "bhd",
  "bmd",
  "brl",
  "cad",
  "chf",
  "clp",
  "cny",
  "czk",
  "dkk",
  "eur",
  "gbp",
  "hkd",
  "huf",
  "idr",
  "ils",
  "inr",
  "jpy",
  "krw",
  "kwd",
  "lkr",
  "mmk",
  "mxn",
  "myr",
  "ngn",
  "nok",
  "nzd",
  "php",
  "pkr",
  "pln",
  "rub",
  "sar",
  "sek",
  "sgd",
  "thb",
  "try",
  "twd",
  "uah",
  "vef",
  "vnd",
  "zar",
  "xdr",
  "xag",
  "xau",
  "bits",
  "sats",
];
export const quickAccessTokens = [
  { symbol: "BTC", label: "Bitcoin" },
  { symbol: "ETH", label: "Ethereum" },
  { symbol: "PAXG", label: "PAX Gold" },
  { symbol: "MKR", label: "Maker" },
  { symbol: "BNB", label: "Binance Coin" },
  { symbol: "LTC", label: "Litecoin" },
  { symbol: "XMR", label: "Monero" },
  { symbol: "BCH", label: "Bitcoin Cash" },
  { symbol: "UNI", label: "Uniswap" },
  { symbol: "AAVE", label: "Aave" },
  { symbol: "SUSHI", label: "Sushi" },
  { symbol: "DASH", label: "DASH" },
];
